name: diffSoundReconstruction
channels:
  - conda-forge
  - defaults
dependencies:
  - python==3.8
  - numpy
  - pandas
  - Pillow
  - diffusers
  - librosa
  - datasets>=2.9.0
  - gradio
  - streamlit
  - tensorboard
  - accelerate
  - transformers
  - torchvision
  - omegaconf
  - pytorch_lightning==1.7.7
  - einops
  - pip
  - pip:
    - bdpy
    - fastl2lir
    - argparse